# fly.toml app configuration file generated for beforeu-backend on 2025-11-30T12:02:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'beforeu-backend'
primary_region = 'bom'

[build]
builder = "paketobuildpacks/builder:full"

[env]
NODE_ENV = "production"
PORT = "5000"

[[services]]
auto_start_machines = true
auto_stop_machines = false
internal_port = 5_000
min_machines_running = 1
processes = [ "app" ]

  [[services.ports]]
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024